### ISSUE TITLE
Why does partial_ratio gives different results then partial ratio in  FuzzyWuzzy lib ?

### ISSUE THREAD

**Issue by Lazart** [maxbachmann/rapidfuzz-cpp#101]
I found that partial_ratio give different results from FuzzyWuzzy, but rapitfuzz clams that it is
"faster, while still providing the same results"
Is this case known and Im missing something or this is a real issue ?

**Comment by maxbachmann** [comment]
The implementation of `partial_ratio` in `fuzzywuzzy` has multiple issues which are fixed in `rapidfuzz`. This can lead to different, but ultimately better results. Examples of this are:
- fuzzywuzzy uses the indel distance if available and falls back to difflib if the Levenshtein library is not installed. This leads to inconsistent result.
- fuzzywuzzy uses the longest common substring as starting point to find the optimal alignment:
  - when using the faster backend it uses a implementation provided by the Levenshtein library which is not made for this purpose and has no guarantee to find the longest common substring
  - even when the longest common substring is found there is no guarantee for it to be the starting point of an optimal alignment

There are quite a few open issues regarding this in the issue tracker of fuzzywuzzy.
rapidfuzz always uses the Indel distance to calculate the final score and uses a sliding window approach to find this optimal alignment, which as far as I can tell is the only way to be guaranteed to find the optimal alignment. So the metric is fundamentally the same, but makes sure the algorithm actually works as expected.

**Comment by Lazart** [comment]
thanks for the very detailed and comprehensive answer
