### ISSUE TITLE
I can't get this to build a library on windows.  

### ISSUE THREAD

**Issue by Stuggy** [maxbachmann/rapidfuzz-cpp#108]
I configured the cmake and got a solution but it doesn't produce a library.

Is there a simpler way to build this on windows or a revision to the cmakelists.txt?

It seems that this wasn't configured to build well on windows.

Thanks for any ideas.

**Comment by maxbachmann** [comment]
I assume with `library` you mean a static / dynamic library. This is expected, since `rapidfuzz-cpp` is a header only library.
You have a couple of options to use the library:
- If the rest of your toolchain is using CMake as well you can directly build against rapidfuzz. Examples of this are shown in https://github.com/maxbachmann/rapidfuzz-cpp/tree/main/examples.
- You can manually set your include paths similar to what cmake would do for you
- I provide a single amalgamated file including the whole library in https://github.com/maxbachmann/rapidfuzz-cpp/blob/main/extras/rapidfuzz_amalgamated.hpp that you can simply include in your project.

**Comment by Stuggy** [comment]
Yes you are correct I want to statically build against a library which is my normal method.

Thanks for the responses and will probably try the amalgamated route.

**Comment by grumagargler** [comment]
It looks like the rapidfuzz_amalgamated.hpp is not compatible with Windows. When I try to compile it, I get many errors about illegal tokens.

**Comment by maxbachmann** [comment]
It should absolutely be compatible with Windows. Here is a simple godbolt demo of using it https://godbolt.org/z/bMhcxh3oM
