### ISSUE TITLE
Issues with building on android

### ISSUE THREAD

**Issue by DavidLazarescu** [maxbachmann/rapidfuzz-cpp#109]
I am porting my [project](https://github.com/Librum-Reader/Librum) that is making use of rapidfuzz-cpp to android. Since rapidfuzz-cpp is written in c+++ i thought that building it on android would work, but I am getting compilation errors:
![image](https://github.com/maxbachmann/rapidfuzz-cpp/assets/69865187/3097c076-3415-4c80-b191-2b309d6e6d57)

Have you ever tested rapidfuzz-cpp on android?

**Comment by DavidLazarescu** [comment]
I have found that that symbol is only defined from __ANDROID_API__ > 28 which is probably causing the problem on my end, so it hopefully has nothing to do with rapidfuzz-cpp.

**Comment by maxbachmann** [comment]
I need an aligned malloc for some of the implementations. This is wrapped in https://github.com/maxbachmann/rapidfuzz-cpp/blob/main/rapidfuzz/details/common.hpp to be OS agnostic, since not all systems provide the same functions to perform an aligned malloc. Could you check how an aligned malloc can be performed on Android previous to this API version and update this section?

**Comment by maxbachmann** [comment]
looking at https://github.com/facebook/folly/blob/ce26dcef47dd3240c483dfd3e8d8607256a0a6d7/folly/Memory.h#L47 it appears we can simply use posix_memalign.

**Comment by DavidLazarescu** [comment]
Yes, I have changed it to this to get it to compile:
![image](https://github.com/maxbachmann/rapidfuzz-cpp/assets/69865187/41c1cd47-8fbf-41bb-9e39-f91fbc6cb369)

And it seems to compile for android.

**Comment by maxbachmann** [comment]
I added this in the main branch.

**Comment by maxbachmann** [comment]
I am still testing a bit, since I made quite a few other changes and will likely release a new version somewhere around new year.
