### ISSUE TITLE
Can I use your library for unicode characters?

### ISSUE THREAD

**Issue by hedgehog91** [maxbachmann/rapidfuzz-cpp#35]
I tried using your library for russian language (unicode characters). For many proposals, it works. But in this case I got the error. Here is a part of code.

`rapidfuzz::fuzz::partial_ratio("альметьевск свидетельство о регистрации сми номер шестнадцать ноль-ноль восемь пятьдесят девять выдано управлением роскомнадзор по республики татарстан одиннадцатого сентября две тысячи двенадцатого года информационная продукция сми предназначена для детей старше двенадцати лет",  "свидетельство о регистрации средства массовой информации");`

I looked where the code falls 
https://github.com/maxbachmann/rapidfuzz-cpp/blob/master/rapidfuzz/details/common_impl.hpp#L155
Unicode characters can be greater than 127 and it will be a value < 0. In this case char_freq index will be out-of-bounds.

Can I just fix ch->static_cast<uint8_t>(ch) for unicode or I can't use this library for unicode because I will get other errors?

**Comment by maxbachmann** [comment]
1) Yes thats a bug it should cast to unsigned before calculating the modulo
2) Do you use the latest version? I do not think, that count_uncommon_chars is still used anywhere in the code base. It was a optimisation for the Levenshtein calculation while it was still O(N*M), but is not needed anymore with the new bitparallel implementation.
3) It depends on what you mean with Unicode support. RapidFuzz treats each code point as a separate character. So e.g. surrogate pairs are treated as multiple characters, even though in Unicode they represent a single character. So UTF32 should be supported, while UTF8 and UTF16 can lead to incorrect similarities.  UTF8/16 could probably be supported by creating string types for them, that return the utf32 equivalent combined characters. However with UTF8/16 there should definetly never be an out of bound access. This is always a bug!!

Could you retry with the latest master version?

**Comment by hedgehog91** [comment]
Thank you for your response!
You are right! I tried the latest version and it works for me. 

If I understood you correctly I should convert utf8/16 to utf32 before calling partial_ratio. Right?

**Comment by maxbachmann** [comment]
Yes in case you want to have correct results for UTF8/16 you should probably convert to UTF32. Apparently this does not mean, that your going to get completely wrong results for UTF8/16. Generally RapidFuzz simply treats every element in the string as a separate character. In UTF32 this is always correct, while in UTF8/16 many characters need multiple elements to represent the character. So e.g. when someone uses a english UTF8 text he can directly use the string since no character spans multiple elements (as long as only the normal alphabet is used)

As an example the first word of your text:
|||
|-----|----------------------|
| text |  альметьевск |
|utf8 | \xd0\xb0\xd0\xbb\xd1\x8c\xd0\xbc\xd0\xb5\xd1\x82\xd1\x8c\xd0\xb5\xd0\xb2\xd1\x81\xd0\xba |
|utf16|\u0430\u043b\u044c\u043c\u0435\u0442\u044c\u0435\u0432\u0441\u043a |
| utf32: | U+00000430U+0000043bU+0000044cU+0000043cU+00000435U+00000442U+0000044cU+00000435U+00000432U+00000441U+0000043a |

Here you can see, that both UTF32 and UTF16 only require one element per character, while UTF8 requires multiple. So it would make sense to convert it to UTF16/32.

**Comment by hedgehog91** [comment]
Thank you! I will close this issue.
