### ISSUE TITLE
JNI implementation of rapidfuzz

### ISSUE THREAD

**Issue by MuntashirAkon** [maxbachmann/rapidfuzz-cpp#57]
Hi,
I have created an Apache-2.0 licensed JNI wrapper around this library. Project URL: https://github.com/MuntashirAkon/rapidfuzz-android

This currently covers fuzz.hpp only. But I've also implemented extractAll and extractOne method as a shorthand. However, I saw some unusual things with the Cached*Ratio classes. Are they all implemented? Also, it would be better if you take a look at the library and suggest changes/features based on your experience with the python version. _This is a new domain for me, so I may miss something._

Regards,
Muntashir

**Comment by maxbachmann** [comment]
The C++ implementation is still in a pretty early state and so some of the interfaces are likely going yo change once I have some more time (currently I am concentrating on the v2.0.0 release of the Python version). When implementing the Python wrapper I faced the following two problems:
1) performance of the wrapper
   - Python is very slow (e.g. calls to Python functions take over 100 ns). So e.g. in extract it is not acceptable to call the scorer function through Python 
       - instead of Python -> extract -> loop -> call scorer
       - use Python -> extract -> somehow get a C pointer to the scorer -> loop -> directly call the scorer through C
   - When matching multiple strings I want to cache some elements, which are reused (e.g. for token_sort_ratio only sort the words in the string once). This is what the Cached*Ratio classes are used for.
   - Support multithreading, which requires me to release the Python global interpreter lock, since Python itself does not really support multithreading.
   - In the future support SIMD to further improve the performance when comparing multiple short strings (e.g. compare 32 8 character strings in parallel using AVX-2)
   - allow for further features like making use of symmetry (func(a, b) == func(b,a)) which is relevant in the cdist implementation
   - Allow extension libraries, which make use of the features above
2) implementing all of the generic features of the extract/extractOne/cdist api
    - scorers might return distances or similarities
    - choices might be a list, a hashmap/dictionary or any other iterable like pandas series
    - strings might be uint8_t/uint16_t/uint32_t, a array, a list of words ...

This has gone through a few iterations, since not all of these requirements have been clear when I first started to write the wrapper. In v2.0.0 I use the following solution:
1) I provide a C Api which allows each scorer to specify a common API to describe them along with function pointers to directly call it through C (and allows the scorer to use features like SIMD)
2) Scorers passing into extract are either pure Python, [PyCapsules](https://docs.python.org/3/c-api/capsule.html) or Python functions "annotated" with PyCapsules. Scorers which are part of RapidFuzz are always annotated, so they can be called in pure Python, but I can still retrieve the C-API in extract. In Python this is relatively simple, since I can use:
```
fuzz.ratio.__RapidFuzzScorer = MyPyCapsule
```
3) When the user enables multithreading unlock the GIL and call the C-API in parallel (if scorers need the GIL e.g. to set a Python exception it has to reaquire the GIL)

Some other remarks:
- Especially to support SIMD the Cached*Ratio API will have to change in the future. 
- The complexity described above is also the reason, why I do not provide extract in C++. It is relatively simple to implement here when the use case is clear, but super hard when it is supposed to be as generic as the Python API without any overhead. 
- At least in Python I do not expose the Cached*Ratio API for two reasons:
  1) it is not really stable yet (at least in case you would like to have a stable API for your wrapper I would not expose them in Java yet)
  2) the overhead to call them makes them pretty worthless in Python (in general people should not directly use scorer in Python if they case about the performance)

**Comment by MuntashirAkon** [comment]
> Python is very slow (e.g. calls to Python functions take over 100 ns). So e.g. in extract it is not acceptable to call the scorer function through Python
> * instead of Python -> extract -> loop -> call scorer
> * use Python -> extract -> somehow get a C pointer to the scorer -> loop -> directly call the scorer through C

In Java, I did it the following way:
1. Create a new instance of Cached*Ratio (i.e. scorer) and pass the pointer address to Java
2. Loop through the items (using a choice generator function per item in order to allow the items to be of any type) in Java
   1. For each choice, fetch ratio/score via a JNI call to the scorer
   2. Do other post processing (such as finding the best score) in Java
3. Free occupied memory by deleting scorer

In my experience, this is the most efficient way to handle these things in Java.

> Support multithreading, which requires me to release the Python global interpreter lock, since Python itself does not really support multithreading.

You've noted that the Cached*Ratio aren't thread-safe. So, I didn't venture into the world of multithreading yet. I'm not actually well-informed about the implications of thread-safety in JNI calls.

> implementing all of the generic features of the extract/extractOne/cdist api

What do you mean by _generic features_? Naturally, I'm more interested in the extract methods than the ratio functions themselves.


> Especially to support SIMD the Cached*Ratio API will have to change in the future.

The whole API or just the inner-workings? The API is very simple having only one constructor and a single public method namely `ratio(string, double)`.

> The complexity described above is also the reason, why I do not provide extract in C++. It is relatively simple to implement here when the use case is clear, but super hard when it is supposed to be as generic as the Python API without any overhead.

This I clearly understand. It's much easier to handle them in Java/Python than in C++. Even if you plan on creating one, I suggest moving them out of the main library. I also feel the same about the `utils` API. There's no reason for it to be part of the main library. The main library should contain no extra features in order to keep it plain and simple. In mobile Android devices, for example, storage is also a major issue. For native libraries, a universal app contains at least four version of the same library in order to support all the supported architectures, and this takes a lot of storage.

> At least in Python I do not expose the Cached*Ratio API for two reasons:
> 1. it is not really stable yet (at least in case you would like to have a stable API for your wrapper I would not expose them in Java yet)
> 2. the overhead to call them makes them pretty worthless in Python (in general people should not directly use scorer in Python if they case about the performance)

Ah, I've already implemented a cached version and using the `CachedWRatio` in one of my projects. At least, this one seems to be working as expected. Although they might be unusable in Python, they can be easily used in Java without much overhead. If they aren't stable, then I will create the extract functions using the normal functions as well until the API becomes stable.

Please keep this issue opened until the Cached*Ratio API becomes stable, and thank you for your insights. They've been very useful.

**Comment by maxbachmann** [comment]
> For each choice, fetch ratio/score via a JNI call to the scorer
In Python this was not possible, since I am able to match upwards to over 100 million strings per second with some ratios, while I can only perform somewhere between 5-10 million calls to a Python function in the same time. However Python functions calls are super slow, so I already expected this to be a lot smaller issue in Java

> You've noted that the Cached*Ratio aren't thread-safe. So, I didn't venture into the world of multithreading yet. I'm not actually well-informed about the implications of thread-safety in JNI calls.

Oh I was wondering how you came to this conclusion. Now I read my own readme and I am confused what the hell I was thinking back then. I fixed this remark: https://github.com/maxbachmann/rapidfuzz-cpp/commit/9268041cc57f264f39afb45781249f1500e0cd8d. They are definetly thread safe and I use them from different threads in my Python implementation as well.

> The whole API or just the inner-workings? The API is very simple having only one constructor and a single public method namely ratio(string, double).

Currently the Api is:
```
constructor(string)
double ratio(string, double)
```
This compares one string passed into the constructor to the string passed into ratio. Using SIMD it would be possible to compare multiple strings to one string in parallel. So the API would be changed to something along the lines of:

```
constructor(string*, string_count) -> possibly an extra overload to use a iterable
constructor(const T<string>&)
void ratio(string, double, double*) -> requires the user to use pre allocated memory for performance reasons
```
which compares string_count elements to a single string. Possibly this could just be a new API instead of changing the current one. I am pretty unhappy with the term Cached*Ratio, but I still do not have any idea for a better name :shrug: 

> This I clearly understand. It's much easier to handle them in Java/Python than in C++. Even if you plan on creating one, I suggest moving them out of the main library. 

I originally implemented them, but it is pretty much impossible to get them as fast as a hand-written solution, which can be written in around 20 lines of code anyways. So I decided to add this code as example in the readme back.

> I also feel the same about the utils API.

The utils API mostly exists to be compatible with FuzzyWuzzy. I plan to provide individual CMake targets for these parts of the library in the future.

> The main library should contain no extra features in order to keep it plain and simple. In mobile Android devices, for example, storage is also a major issue. 

At least for C++ this is a non-issue, since this library is mostly header only (only utils is not since it requires a large lookup table). So what you do not use will not end up in the binary. Obviously for a Wrapper used in a different language this is a decision the author of the wrapper has to make. In Python I did not really care about storage.

> For native libraries, a universal app contains at least four version of the same library in order to support all the supported architectures, and this takes a lot of storage.

I have no experience with android. Is there any reason why the play store can not detect the correct hardware architecture at install time and then install the correct version?

> Ah, I've already implemented a cached version and using the CachedWRatio in one of my projects. At least, this one seems to be working as expected. Although they might be unusable in Python, they can be easily used in Java without much overhead.

Yes they work just fine (the Python wrapper uses them internally). They are just not faster when called from Python, since performance is heavily bound by the function call overhead.

> Please keep this issue opened until the Cached*Ratio API becomes stable, and thank you for your insights. They've been very useful.

Sure I will let you know once they are

**Comment by MuntashirAkon** [comment]
> Is there any reason why the play store can not detect the correct hardware architecture at install time and then install the correct version?

The trouble is, Play Store is currently the only app market which properly supports them. Other app markets such as Amazon Store or F-Droid do not support architecture-specific APKs (well, F-Droid does support it but the configuration is very complicated and has to configure manually every time a new release is made). As a result, the APK files usually contain binary files for all the supported platforms.

> Possibly this could just be a new API instead of changing the current one.

Yeah, I agree.

> I am pretty unhappy with the term Cached*Ratio, but I still do not have any idea for a better name

Ha ha, I think they're fine.

**Comment by maxbachmann** [comment]
After thinking about this a bit more and checking your usage I decided to change the APIs a bit for the 1.0.0 release. A couple of notes on your code:
```
JNIEXPORT jdouble JNICALL Java_io_github_muntashirakon_rapidfuzz_RapidFuzz_nativeRatio
  (JNIEnv *env, jclass clazz, jstring s1, jstring s2, jdouble score_cuttoff) {
    const char* str1 = env->GetStringUTFChars(s1, NULL);
    const char* str2 = env->GetStringUTFChars(s2, NULL);
    return (double) fuzz::ratio(str1, str2, (double) score_cuttoff);
}
```
1) You have to call `ReleaseStringUTFChars`. Your usage will either leak memory (if `GetStringUTFChars` allocates a new string) or causes the JVM to believe you need the memory indefinitely. Either way this leads to a memory leak.
2) You might want to catch exceptions. For most of the scorers exceptions can only occur when your out of memory. However since these strings might be user defined strings, this could be used to trigger a segmentation fault.
```
JNIEXPORT jlong JNICALL Java_io_github_muntashirakon_rapidfuzz_RapidFuzzCached_nativeNewCachedRatio
  (JNIEnv *env, jclass clazz, jstring query) {
    const char* q = env->GetStringUTFChars(query, NULL);
    fuzz::CachedRatio<std::string> *scorer = new fuzz::CachedRatio(std::string(q));
    return (jlong) scorer;
}
```
This will currently not work, since I do not copy the string passed into the constructor. So right now this will later access freed memory when you call ratio (In 1.0.0 I will make a copy to prevent this kind of error)

**Comment by MuntashirAkon** [comment]
Thank you for your review. I will look into the issues.

**Comment by maxbachmann** [comment]
@MuntashirAkon  i finished the implementation, but I am still working on an improved test coverage and documentation. I hope to release v1.0.0 during this week.

**Comment by MuntashirAkon** [comment]
Thank you.
