### ISSUE TITLE
Typos in code

### ISSUE THREAD

**Issue by ithersta** [maxbachmann/rapidfuzz-cpp#60]
I think I found a typo. `tokens_a` emptiness is checked twice.
https://github.com/maxbachmann/rapidfuzz-cpp/blob/4afd61ee3dcd2895362750308361b2e13ea24275/rapidfuzz/fuzz.impl#L389
Also here:
https://github.com/maxbachmann/rapidfuzz-cpp/blob/4afd61ee3dcd2895362750308361b2e13ea24275/rapidfuzz/fuzz.impl#L488

**Comment by maxbachmann** [comment]
Yes this is a typo. Note that it still worked correctly, since this condition is only really required for the case `len1 == len2 == 0`. When only one of the lengths is 0 the subsequent implementation will result in 0 anyways. Fixed the typo in https://github.com/maxbachmann/rapidfuzz-cpp/commit/2ff2a6a19aec02557b66b4de05d3c57e698ae75d.
